<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<title><?=$this->pageTitle ?></title>

<link rel="stylesheet" href="<?=Class_Server::extUrl()?>/reset-backend.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=Class_Server::libUrl()?>/admin/style/structure.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="<?=Class_Server::libUrl()?>/admin/style/backend.css" type="text/css" media="screen" rel="stylesheet">

<script type="text/javascript" src="<?=Class_Server::extUrl()?>/jub.js"></script>
<script type="text/javascript" src="<?=Class_Server::extUrl()?>/ajax-select-grid.js"></script>
<script type="text/javascript" src="<?=Class_Server::libUrl()?>/admin/script/admin.js"></script>
<script type="text/javascript" src="<?=Class_Server::libUrl()?>/admin/script/back.js"></script>

<!-- 
<script type="text/javascript" src="<?=Class_Server::libUrl()?>/v1/script/jqpager.js"></script>
<script type="text/javascript" src="<?=Class_Server::libUrl()?>/v1/script/admin-back.js"></script>
<script type="text/javascript" src="<?=Class_Server::libUrl()?>/v1/script/return-button.js"></script>
<script type="text/javascript" src="<?=Class_Server::libUrl()?>/v1/script/My97DatePicker/WdatePicker.js"></script>
<script type="text/javascript" src="<?=Class_Server::libUrl()?>/v1/script/jquery.messager.js"></script>
<link rel="stylesheet" href="<?=Class_Server::libUrl()?>/v1/style/detailcreate.css" type="text/css" media="screen, projection">

 -->

