<div id='title'>福网互联科技有限公司</div><br>
<div id='table'>个人信息中心</div><br><br><br>
<form action="/pm/individual/editpwd/" method="post" id="editpwd" style="font-size:16px;margin-left:20%;">
	<table width="80%" border="0" cellpadding="0" cellspacing="0">
	  <tr>
	    <td width="45%" height="35" align="right">输入现用密码：</td>
	    <td ><input type="password" name="oldpwd" id="oldpwd" /><p id='oldmessage' style="float:right;display:inline;color:#f00;width:350px;"></p></td>
	  </tr>
	  <tr>
	    <td height="35" align="right">输入新密码：</td>
	    <td><input type="password" name="newpwd" id="newpwd" /></td>
	  </tr>
	  <tr>
	    <td height="35" align="right">确认新密码：</td>
	    <td><input type="password" name="zspwd" id="zspwd" /><p id='newmessage' style="float:right;display:inline;color:#f00;width:350px;"></p></td>
	  </tr>
	  <tr>
	    <td height="35" colspan="2" align="center">
	    <input type="submit" name="button" id="button" value="确定" onclick="javascript:return check();" />
	    <input type="button" name="button2" id="button2" value="返回" /></td>
	  </tr>
	</table>
</form>
<script type="text/javascript">
var i="";
function check(){
	if(i==0){alert('有错误，请重新输入！');return false;}
	var newpwd = document.getElementById("newpwd").value;
	var zspwd = document.getElementById("zspwd").value;
	if(newpwd == zspwd){
		return true;
	}else{
		alert('有错误，请重新输入！');
		return false;
	} 
}
$(document).ready(function() { 
	$('#editpwd #oldpwd').blur(function(){
		var oldpwd = $(this).val();
		$.ajax({
			type: "POST",
			url: '/pm/index/selpwd/oldpwd/'+oldpwd,
			success: function(obj) {
				if(obj == 0){
					var aa = "×&nbsp原密码错误，请重新输入！";
					i=0;
				}else{
					var aa = "√";
					i=1;
				}
				$("#editpwd #oldmessage").html(aa);		
			}
		});
	});
	$('#editpwd #zspwd').blur(function(){
		var newpwd = $('#editpwd #newpwd').val();
		var zspwd = $(this).val();
		if(newpwd == zspwd){
			var aa = "√";
		}else{
			var aa = "×&nbsp两次输入密码错误，请重新输入！";
		} 
		$("#editpwd #newmessage").html(aa);	
	});
});
</script>