<table id="detailstep" width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size:16px;" >
  <tr align="center">
  	<td height="53" style="vertical-align:middle;">项目名称</td>
    <td style="vertical-align:middle;">任务内容</td>
    <td style="vertical-align:middle;">完成人员</td>
    <td style="vertical-align:middle;">完成进度</td>
    <td style="vertical-align:middle;">上传路径</td>
    <td style="vertical-align:middle;">开始时间 </td>
    <td style="vertical-align:middle;">结束时间</td>
    <td style="vertical-align:middle;">状态</td>
    <td style="vertical-align:middle;">点评</td>
    <td style="vertical-align:middle;"><?php if($this->sid == 0){echo '操作';}?></td>
  </tr>
  <?php foreach ($this->rowset as $num => $arrone){?>
  <?php if($arrone['entrustid']!=''){ ?>
		   <tr align="center" >
		    <td height="64" style="vertical-align:middle;" rowspan="2"><a href='/pm/detail/index/id/<?php echo $arrone['detailId'];?>'><?php echo $arrone['projectName']?></a></td>
		    <td style="vertical-align:middle;"><?php echo $arrone['content'];?></td>
		    <td style="vertical-align:middle;"><?php echo $arrone['userName'];?></td>
		    <td style="vertical-align:middle;" rowspan="2"><?php echo $arrone['percentage'];?></td>
		    <td style="vertical-align:middle;" rowspan="2"><?php 
			    $arrbox = explode("&", $arrone['pathurl']);
			    for($i=0;$i<count($arrbox);$i++){
			    	echo $arrbox[$i]."<br>";
			    }
		    ?></td>
		    <td style="vertical-align:middle;" rowspan="2"><?php echo $arrone['startTime'];?></td>
		    <td style="vertical-align:middle;" rowspan="2"><?php echo $arrone['endTime'];?></td>
		    <td style="vertical-align:middle;" rowspan="2"><?php if($arrone['state'] == 0){echo '进行中';}else{echo '完成';}?></td>
		    <td style="vertical-align:middle;" rowspan="2"><?php echo $arrone['assess']?></td>
		    <td style="vertical-align:middle;" rowspan="2"><?php if($arrone['userId'] == $_SESSION['USERID']){?><a href='/pm/individual/edit/id/<?php echo $arrone['id'];?>'>编辑</a>&nbsp;<?php }?></td>
		  </tr>
		  <tr align="center" >
		    <td height="32" style="color:#f00;vertical-align:middle;">┗━委托☞</td>
		    <td style="vertical-align:middle;"><?php echo $arrone['entrustName'];?></td>
		  </tr>
	 <?php }else {?>
	 	<tr align="center" valign="middle">
	 	<td height="32" style="vertical-align:middle;"><a href='/pm/detail/index/id/<?php echo $arrone['detailId'];?>'><?php echo $arrone['projectName']?></a></td>
	    <td style="vertical-align:middle;"><?php echo $arrone['content']?></td>
	    <td style="vertical-align:middle;"><?php echo $arrone['userName']?></td>
	    <td style="vertical-align:middle;"><?php echo $arrone['percentage']?></td>
	    <td style="vertical-align:middle;"><?php 
		    $arrbox = explode("&", $arrone['pathurl']);
		    for($i=0;$i<count($arrbox);$i++){
		    	echo $arrbox[$i]."<br>";
		    }
	    ?></td>
	    <td style="vertical-align:middle;"><?php echo $arrone['startTime']?></td>
	    <td style="vertical-align:middle;"><?php echo $arrone['endTime']?></td>
	    <td style="vertical-align:middle;"><?php if($arrone['state'] == 0){echo '进行中';}else{echo '完成';}?></td>
	    <td style="vertical-align:middle;"><?php echo $arrone['assess']?></td>
	    <td style="vertical-align:middle;"><?php if($this->sid == 0){?><a href='/pm/individual/edit/id/<?php echo $arrone['id'];?>'>编辑</a>&nbsp;
	    &nbsp;<a href='/pm/entrust/create/id/<?php echo $arrone['id'];?>'>委托</a><?php }?></td>
	  </tr>
  <?php }}?>
  <tr align="center">
    <td height="66" colspan="9"><br><?php echo $this->pageshow;?></td>
  </tr>
</table>