<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<title><?=$this->pageTitle ?></title>

<link rel="stylesheet" href="http://library.enorange.com/ext/reset.css" type="text/css" media="screen, projection">
<script type="text/javascript" src="http://library.enorange.com/ext/jquery-1.7.1.js"></script>
<script type="text/javascript" src="http://library.enorange.com/ext/underscore-1.2.0.js"></script>
<script type="text/javascript" src="http://library.enorange.com/ext/backbone-0.5.3.js"></script>
<script type="text/javascript" src="http://library.enorange.com/v1/script/ajax-select-grid.js"></script>

<script type="text/javascript" src="http://lib.eo.test/form/script/main.js"></script>
<script type="text/javascript" src="http://lib.eo.test/ext/jquery.ndd.js"></script>
<script type="text/javascript" src="http://lib.eo.test/v1/script/admin-drag.js"></script>





<link rel="stylesheet" href="http://library.enorange.com/v1/style/template.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="http://library.enorange.com/v1/style/admin-structure.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="http://library.enorange.com/v1/style/admin-backend.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="http://lib.eo.test/form/style/form-editor.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="http://lib.eo.test/v1/style/admin.css" type="text/css" media="screen" rel="stylesheet">

<script type="text/javascript" src="http://lib.eo.test/v1/script/jqpager.js"></script>
<script type="text/javascript" src="http://lib.eo.test/v1/script/admin-back.js"></script>
<script type="text/javascript" src="http://lib.eo.test/v1/script/return-button.js"></script>
<script type="text/javascript" src="http://lib.eo.test/v1/script/My97DatePicker/WdatePicker.js"></script>
<script type="text/javascript" src="http://lib.eo.test/v1/script/jquery.messager.js"></script>
<link rel="stylesheet" href="http://lib.eo.test/v1/style/detailcreate.css" type="text/css" media="screen, projection">

