<div id='title'>福网互联科技有限公司</div><br>
<div id='table'>项目添加表</div><br>
 <?php echo $this->html;?>

<script type='text/javascript'>
$(document).ready(function() { 
	$('#button').attr("onclick","javascript:return check();");
	var aa="<br><div id='itemamount_explain' style='color:#f00;'></div>";
	$("#itemamount-element").append(unescape(aa));
});
function check(){
	var itemamount = $("#itemamount").val();
	var paid = $("#paid").val();
	if(itemamount){
		if(!isNaN(itemamount)){
			if(itemamount){
				if(!isNaN(paid)){
					if(itemamount>paid){
						return true;
					}else{
						var aa="已付金额不能大于项目金额";
						$("#itemamount_explain").html(aa);
						return false;
					}
				}else{
					var aa="请填写正确的已付金额";
					$("#itemamount_explain").html(aa);
					return false;
				}
			}
		}else{
			var aa="请填写正确的价格";
			$("#itemamount_explain").html(aa);
			return false;
		}
	}else{
		var aa="价格不能为空";
		$("#itemamount_explain").html(aa);
		return false;
	}
}
</script>