<script type="text/javascript" src="http://lib.eo.test/v1/script/My97DatePicker/WdatePicker.js"></script>
<script type="text/javascript">
$(document).ready(function() { 
	$('#starttime').attr("onclick","WdatePicker({lang:'zh-cn'})");
	$('#endtime').attr("onclick","WdatePicker({lang:'zh-cn'})");
});
</script>
<div id='title'>福网互联科技有限公司</div><br>
<div id='table'>项目步骤部署表</div><br>
<?php echo $this->form;?>
