<table id="detailstep" width="100%" border="0" cellpadding="0" cellspacing="0" style="font-size:16px;">
  <tr align="center">
    <td height="60" colspan="9"><div id='title'>福网互联科技有限公司</div><br>
		<div id='table'>项目<font color="#f00"><?php echo $this->projectname;?></font>步骤进行表</div><br></td>
  </tr>
  <tr align="center">
  	<td height="35">项目名称</td>
  	<td>联系方式</td>
  	<td>项目类型</td>
  	<td>项目金额</td>
  	<td>已付金额</td>
  	<td>测试地址</td>
  	<td>域名</td>
  	<td>状态</td>
  	<td>操作</td>
  </tr>
  <tr id="detailinformation" align="center">
  	<td height="35"><?php echo $this->detailrow['projectname'];?></td>
  	<td><?php echo $this->detailrow['contact'];?></td>
  	<td><?php echo $this->detailrow['type'];?></td>
  	<td><?php echo $this->detailrow['itemamount'];?></td>
  	<td><?php echo $this->detailrow['paid'];?></td>
  	<td><?php echo $this->detailrow['testurl'];?></td>
  	<td><?php echo $this->detailrow['domain'];?></td>
  	<td><?php echo $this->detailrow['state'];?></td>
  	<td><a href='/pm/detail/edit/id/<?php echo $this->detailrow['id'];?>'>编辑</a>
  	&nbsp;&nbsp;<a href='/pm/detail/del/id/<?php echo $this->detailrow['id'];?>'>删除</a></td>
  </tr>
  <tr align="center"><td height="30" colspan="9"></td></tr>
  <tr align="center" valign="middle">
    <td height="35">任务内容</td>
    <td>完成人员</td>
    <td>完成进度</td>
    <td>上传路径</td>
    <td>开始时间 </td>
    <td>结束时间</td>
    <td>状态</td>
    <td>点评</td>
    <td>操作</td>
  </tr>
  <?php if(empty($this->row)){echo "<tr><td height='32' align='center'>暂无步骤，请添加！</td><td colspan='3'>&nbsp;</td></tr>";}else{?>
  <?php foreach ($this->row as $num => $arrone){?>
  <tr align="center" valign="middle">
    <td height="32"><?php echo $arrone['content']?></td>
    <td><?php echo $arrone['username']?></td>
    <td><?php echo $arrone['percentage']?></td>
    <td><?php 
	    $arrbox = explode("&", $arrone['pathurl']);
	    for($i=0;$i<count($arrbox);$i++){
	    	echo $arrbox[$i]."<br>";
	    }
    ?></td>
    <td><?php echo $arrone['starttime']?></td>
    <td><?php echo $arrone['endtime']?></td>
    <td><?php if($arrone['state'] == 0){echo '进行中';}else{echo '完成';}?></td>
    <td><?php echo $arrone['assess']?></td>
    <td><a href='/pm/step/distribution/id/<?php echo $arrone['id'];?>'>分发任务</a>&nbsp;
    &nbsp;<a href='/pm/step/edit/deid/<?php echo $this->deid;?>/id/<?php echo $arrone['id'];?>'>编辑</a>&nbsp;
    &nbsp;<a href='/pm/step/del/deid/<?php echo $this->deid;?>/id/<?php echo $arrone['id'];?>'>删除</a></td>
  </tr>
  <?php }}?>
  </table>
  <input id="detailid" type="hidden" value="<?php echo $this->deid;?>">
  <table id="add" width="15%" style="font-size:16px;" >
	  <tr align="right">
	  	<td><a id ="addstep" href="#">添加步骤</a>&nbsp;&nbsp;&nbsp;&nbsp;<a id ="submitstep">确定</a>&nbsp;&nbsp;</td>
	  </tr>
  </table>
<script type="text/javascript">
var i=10;
$('#addstep').click(function(){
	i++;
	var aa="<tr id=s"+i+" align='center'><td><input type='text' value=''/></td>";
	aa+="<td align='left'><select id='skillid"+i+"' class='seltype'>";
	<?php foreach ($this->selrow as $num => $arrtwo){?>
	aa+="<option value='<?php echo $arrtwo['id'];?>'><?php echo $arrtwo['skillname']?></option>";
	<?php }?>
	aa+="</select>";
	aa+="&nbsp;<input id='deloption' type='button' value='删除' class=s"+i+"></td><td height='32' colspan='7'>&nbsp;</td></tr>";
	$("#detailstep").append(unescape(aa));
	return false;
});
$('#deloption').live("click",function(){
	var s = $(this).attr("class");
	$("#"+s).remove();
});
$('#submitstep').click(function(){
	var attrValue="";
	var selvalue="";
	var j=1;
	$("#detailstep :input:text").each(function(){
		var value = $(this).attr("value");
		if(value == ''){j=0;return false;}
		attrValue+= value + ':';
	});
	if(j == 0){alert("任务步骤不能为空！");return false;}
	$("#detailstep .seltype").each(function(){
		var id = $(this).val(); 
		selvalue+=id+':';		
	});
	var id = $("#detailid").val();
	var aj = $.ajax({
		type: "POST",
		url: '/pm/step/create/id/'+id+'/val/'+attrValue+'/selval/'+selvalue,
		success: function(obj) {	
			window.location.href='/pm/step/index/id/'+id;	
		}
	});
});
</script>
    
    