<table width="95%" border="0" align="center" cellpadding="0" cellspacing="0" style="font-size:16px;">
  <tr>
    <td height="32" colspan="4">
    	<div id='title'>福网互联科技有限公司</div><input type="hidden" value="<?php echo $this->deid;?>" id="deid"> <br>
		<div id='table'>项目<font color="#f00"><?php echo $this->projectName;?></font>客户反馈意见表</div><br></td>
  </tr>
  <tr>
    <td height="32" align="center">时间</td>
    <td align="center">附件路径</td>
    <td align="center">反馈意见</td>
    <td align="center">操作</td>
  </tr>
  <?php if(empty($this->row)){echo "<tr><td height='32' align='center'>暂无反馈意见</td><td colspan='3'>&nbsp;</td></tr>";}else{?>
  <?php foreach ($this->row as $num => $arrone){?>
  <tr align="center">
    <td height="32"><?php echo $arrone['feedbackTime']?></td>
    <td><?php echo $arrone['pathurl'];?></td>
    <td><?php echo $arrone['proposal'];?></td>
    <td><a id="editfeedback" href="/pm/feedback/edit/id/<?php echo $arrone['id'];?>">修改</a>
    &nbsp;&nbsp;<a id="editfeedback" href="/pm/feedback/del/deid/<?php echo $arrone['detailId'];?>/id/<?php echo $arrone['id'];?>">删除</a></td>
  </tr>
  <?php }}?>
  <tr>
    <td height="32">&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>